version: '3'
services:
  server:
    image: simple-rpc-server:latest

  client:
    image: simple-rpc-client:latest
    depends_on:
      - server

  client-python:
    image: simple-rpc-client-python:latest
    depends_on:
      - server